package cn.org.upbnc.xmlcompare;

public class BfdUtils {
    public static String running() {
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<data xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n" +
                "  <bfd xmlns=\"http://www.huawei.com/netconf/vrp/huawei-bfd\">\n" +
                "    <bfdCfgSessions>\n" +
                "      <bfdCfgSession>\n" +
                "        <sessName>Tunnel1_Master</sessName>\n" +
                "        <localDiscr>34</localDiscr>\n" +
                "        <remoteDiscr>35</remoteDiscr>\n" +
                "        <minTxInt>3</minTxInt>\n" +
                "        <minRxInt>33</minRxInt>\n" +
                "        <detectMulti>3</detectMulti>\n" +
                "        <tosExp>7</tosExp>\n" +
                "        <adminDown>false</adminDown>\n" +
                "        <linkType>TE_LSP</linkType>\n" +
                "        <createType>SESS_STATIC</createType>\n" +
                "        <tunnelName>Tunnel1</tunnelName>\n" +
                "        <teBackup>false</teBackup>\n" +
                "        <processPst>false</processPst>\n" +
                "        <pis>false</pis>\n" +
                "        <pisSubIf>false</pisSubIf>\n" +
                "        <useDefaultIp>false</useDefaultIp>\n" +
                "        <addrType>IPV4</addrType>\n" +
                "        <autoCalc>false</autoCalc>\n" +
                "        <pwSecondary>false</pwSecondary>\n" +
                "        <isSetTrackIf>false</isSetTrackIf>\n" +
                "        <oneArmEcho>false</oneArmEcho>\n" +
                "        <bundleMode>-</bundleMode>\n" +
                "        <pisNoImpact>false</pisNoImpact>\n" +
                "        <bfdSessRunning>\n" +
                "          <udpDstPort>3784</udpDstPort>\n" +
                "          <detectMode>ASYNC_WITHOUT_ECHO</detectMode>\n" +
                "          <sessState>DOWN</sessState>\n" +
                "          <localDiscr>34</localDiscr>\n" +
                "          <ttl>1</ttl>\n" +
                "          <notUpReason>Board-selecting-failed</notUpReason>\n" +
                "          <localDiag>NONE</localDiag>\n" +
                "          <remoteDiscr>35</remoteDiscr>\n" +
                "          <minTxInt>3</minTxInt>\n" +
                "          <minRxInt>33</minRxInt>\n" +
                "        </bfdSessRunning>\n" +
                "      </bfdCfgSession>\n" +
                "      <bfdCfgSession>\n" +
                "        <sessName>Tunnel1_Tunnel</sessName>\n" +
                "        <localDiscr>3</localDiscr>\n" +
                "        <remoteDiscr>3</remoteDiscr>\n" +
                "        <minTxInt>3</minTxInt>\n" +
                "        <minRxInt>22</minRxInt>\n" +
                "        <detectMulti>3</detectMulti>\n" +
                "        <tosExp>7</tosExp>\n" +
                "        <adminDown>false</adminDown>\n" +
                "        <linkType>TE_TUNNEL</linkType>\n" +
                "        <createType>SESS_STATIC</createType>\n" +
                "        <tunnelName>Tunnel1</tunnelName>\n" +
                "        <teBackup>false</teBackup>\n" +
                "        <processPst>false</processPst>\n" +
                "        <pis>false</pis>\n" +
                "        <pisSubIf>false</pisSubIf>\n" +
                "        <useDefaultIp>false</useDefaultIp>\n" +
                "        <addrType>IPV4</addrType>\n" +
                "        <autoCalc>false</autoCalc>\n" +
                "        <pwSecondary>false</pwSecondary>\n" +
                "        <isSetTrackIf>false</isSetTrackIf>\n" +
                "        <oneArmEcho>false</oneArmEcho>\n" +
                "        <bundleMode>-</bundleMode>\n" +
                "        <pisNoImpact>false</pisNoImpact>\n" +
                "        <bfdSessRunning>\n" +
                "          <udpDstPort>3784</udpDstPort>\n" +
                "          <detectMode>ASYNC_WITHOUT_ECHO</detectMode>\n" +
                "          <sessState>DOWN</sessState>\n" +
                "          <localDiscr>3</localDiscr>\n" +
                "          <ttl>1</ttl>\n" +
                "          <notUpReason>Board-selecting-failed</notUpReason>\n" +
                "          <localDiag>NONE</localDiag>\n" +
                "          <remoteDiscr>3</remoteDiscr>\n" +
                "          <minTxInt>3</minTxInt>\n" +
                "          <minRxInt>22</minRxInt>\n" +
                "        </bfdSessRunning>\n" +
                "      </bfdCfgSession>\n" +
                "    </bfdCfgSessions>\n" +
                "  </bfd>\n" +
                "</data>";
    }

    public static String add() {
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<data xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n" +
                "  <bfd xmlns=\"http://www.huawei.com/netconf/vrp/huawei-bfd\">\n" +
                "    <bfdCfgSessions>\n" +
                "      <bfdCfgSession>\n" +
                "        <sessName>Tunnel1_Master</sessName>\n" +
                "        <localDiscr>34</localDiscr>\n" +
                "        <remoteDiscr>35</remoteDiscr>\n" +
                "        <minTxInt>3</minTxInt>\n" +
                "        <minRxInt>33</minRxInt>\n" +
                "        <detectMulti>3</detectMulti>\n" +
                "        <tosExp>7</tosExp>\n" +
                "        <adminDown>false</adminDown>\n" +
                "        <linkType>TE_LSP</linkType>\n" +
                "        <createType>SESS_STATIC</createType>\n" +
                "        <tunnelName>Tunnel1</tunnelName>\n" +
                "        <teBackup>false</teBackup>\n" +
                "        <processPst>false</processPst>\n" +
                "        <pis>false</pis>\n" +
                "        <pisSubIf>false</pisSubIf>\n" +
                "        <useDefaultIp>false</useDefaultIp>\n" +
                "        <addrType>IPV4</addrType>\n" +
                "        <autoCalc>false</autoCalc>\n" +
                "        <pwSecondary>false</pwSecondary>\n" +
                "        <isSetTrackIf>false</isSetTrackIf>\n" +
                "        <oneArmEcho>false</oneArmEcho>\n" +
                "        <bundleMode>-</bundleMode>\n" +
                "        <pisNoImpact>false</pisNoImpact>\n" +
                "        <bfdSessRunning>\n" +
                "          <udpDstPort>3784</udpDstPort>\n" +
                "          <detectMode>ASYNC_WITHOUT_ECHO</detectMode>\n" +
                "          <sessState>DOWN</sessState>\n" +
                "          <localDiscr>34</localDiscr>\n" +
                "          <ttl>1</ttl>\n" +
                "          <notUpReason>Board-selecting-failed</notUpReason>\n" +
                "          <localDiag>NONE</localDiag>\n" +
                "          <remoteDiscr>35</remoteDiscr>\n" +
                "          <minTxInt>3</minTxInt>\n" +
                "          <minRxInt>33</minRxInt>\n" +
                "        </bfdSessRunning>\n" +
                "      </bfdCfgSession>\n" +
                "      <bfdCfgSession>\n" +
                "        <sessName>Tunnel1_Tunnel</sessName>\n" +
                "        <localDiscr>3</localDiscr>\n" +
                "        <remoteDiscr>3</remoteDiscr>\n" +
                "        <minTxInt>3</minTxInt>\n" +
                "        <minRxInt>22</minRxInt>\n" +
                "        <detectMulti>3</detectMulti>\n" +
                "        <tosExp>7</tosExp>\n" +
                "        <adminDown>false</adminDown>\n" +
                "        <linkType>TE_TUNNEL</linkType>\n" +
                "        <createType>SESS_STATIC</createType>\n" +
                "        <tunnelName>Tunnel1</tunnelName>\n" +
                "        <teBackup>false</teBackup>\n" +
                "        <processPst>false</processPst>\n" +
                "        <pis>false</pis>\n" +
                "        <pisSubIf>false</pisSubIf>\n" +
                "        <useDefaultIp>false</useDefaultIp>\n" +
                "        <addrType>IPV4</addrType>\n" +
                "        <autoCalc>false</autoCalc>\n" +
                "        <pwSecondary>false</pwSecondary>\n" +
                "        <isSetTrackIf>false</isSetTrackIf>\n" +
                "        <oneArmEcho>false</oneArmEcho>\n" +
                "        <bundleMode>-</bundleMode>\n" +
                "        <pisNoImpact>false</pisNoImpact>\n" +
                "        <bfdSessRunning>\n" +
                "          <udpDstPort>3784</udpDstPort>\n" +
                "          <detectMode>ASYNC_WITHOUT_ECHO</detectMode>\n" +
                "          <sessState>DOWN</sessState>\n" +
                "          <localDiscr>3</localDiscr>\n" +
                "          <ttl>1</ttl>\n" +
                "          <notUpReason>Board-selecting-failed</notUpReason>\n" +
                "          <localDiag>NONE</localDiag>\n" +
                "          <remoteDiscr>3</remoteDiscr>\n" +
                "          <minTxInt>3</minTxInt>\n" +
                "          <minRxInt>22</minRxInt>\n" +
                "        </bfdSessRunning>\n" +
                "      </bfdCfgSession>\n" +
                "\t  <bfdCfgSession>\n" +
                "        <sessName>Tunnel2_Tunnel</sessName>\n" +
                "        <localDiscr>3</localDiscr>\n" +
                "        <remoteDiscr>3</remoteDiscr>\n" +
                "        <minTxInt>3</minTxInt>\n" +
                "        <minRxInt>22</minRxInt>\n" +
                "        <detectMulti>3</detectMulti>\n" +
                "        <tosExp>7</tosExp>\n" +
                "        <adminDown>false</adminDown>\n" +
                "        <linkType>TE_TUNNEL</linkType>\n" +
                "        <createType>SESS_STATIC</createType>\n" +
                "        <tunnelName>Tunnel1</tunnelName>\n" +
                "        <teBackup>false</teBackup>\n" +
                "        <processPst>false</processPst>\n" +
                "        <pis>false</pis>\n" +
                "        <pisSubIf>false</pisSubIf>\n" +
                "        <useDefaultIp>false</useDefaultIp>\n" +
                "        <addrType>IPV4</addrType>\n" +
                "        <autoCalc>false</autoCalc>\n" +
                "        <pwSecondary>false</pwSecondary>\n" +
                "        <isSetTrackIf>false</isSetTrackIf>\n" +
                "        <oneArmEcho>false</oneArmEcho>\n" +
                "        <bundleMode>-</bundleMode>\n" +
                "        <pisNoImpact>false</pisNoImpact>\n" +
                "        <bfdSessRunning>\n" +
                "          <udpDstPort>3784</udpDstPort>\n" +
                "          <detectMode>ASYNC_WITHOUT_ECHO</detectMode>\n" +
                "          <sessState>DOWN</sessState>\n" +
                "          <localDiscr>3</localDiscr>\n" +
                "          <ttl>1</ttl>\n" +
                "          <notUpReason>Board-selecting-failed</notUpReason>\n" +
                "          <localDiag>NONE</localDiag>\n" +
                "          <remoteDiscr>3</remoteDiscr>\n" +
                "          <minTxInt>3</minTxInt>\n" +
                "          <minRxInt>22</minRxInt>\n" +
                "        </bfdSessRunning>\n" +
                "      </bfdCfgSession>\n" +
                "    </bfdCfgSessions>\n" +
                "  </bfd>\n" +
                "</data>";
    }

    public static String modify() {
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<data xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n" +
                "  <bfd xmlns=\"http://www.huawei.com/netconf/vrp/huawei-bfd\">\n" +
                "    <bfdCfgSessions>\n" +
                "      <bfdCfgSession>\n" +
                "        <sessName>Tunnel1_Master</sessName>\n" +
                "        <localDiscr>34</localDiscr>\n" +
                "        <remoteDiscr>35</remoteDiscr>\n" +
                "        <minTxInt>3</minTxInt>\n" +
                "        <minRxInt>33</minRxInt>\n" +
                "        <detectMulti>3</detectMulti>\n" +
                "        <tosExp>7</tosExp>\n" +
                "        <adminDown>false</adminDown>\n" +
                "        <linkType>TE_LSP</linkType>\n" +
                "        <createType>SESS_STATIC</createType>\n" +
                "        <tunnelName>Tunnel1</tunnelName>\n" +
                "        <teBackup>false</teBackup>\n" +
                "        <processPst>false</processPst>\n" +
                "        <pis>false</pis>\n" +
                "        <pisSubIf>false</pisSubIf>\n" +
                "        <useDefaultIp>false</useDefaultIp>\n" +
                "        <addrType>IPV4</addrType>\n" +
                "        <autoCalc>false</autoCalc>\n" +
                "        <pwSecondary>false</pwSecondary>\n" +
                "        <isSetTrackIf>false</isSetTrackIf>\n" +
                "        <oneArmEcho>false</oneArmEcho>\n" +
                "        <bundleMode>-</bundleMode>\n" +
                "        <pisNoImpact>false</pisNoImpact>\n" +
                "        <bfdSessRunning>\n" +
                "          <udpDstPort>3784</udpDstPort>\n" +
                "          <detectMode>ASYNC_WITHOUT_ECHO</detectMode>\n" +
                "          <sessState>DOWN</sessState>\n" +
                "          <localDiscr>34</localDiscr>\n" +
                "          <ttl>1</ttl>\n" +
                "          <notUpReason>Board-selecting-failed</notUpReason>\n" +
                "          <localDiag>NONE</localDiag>\n" +
                "          <remoteDiscr>35</remoteDiscr>\n" +
                "          <minTxInt>3</minTxInt>\n" +
                "          <minRxInt>34</minRxInt>\n" +
                "        </bfdSessRunning>\n" +
                "      </bfdCfgSession>\n" +
                "      <bfdCfgSession>\n" +
                "        <sessName>Tunnel1_Tunnel</sessName>\n" +
                "        <localDiscr>3</localDiscr>\n" +
                "        <remoteDiscr>3</remoteDiscr>\n" +
                "        <minTxInt>3</minTxInt>\n" +
                "        <minRxInt>22</minRxInt>\n" +
                "        <detectMulti>3</detectMulti>\n" +
                "        <tosExp>7</tosExp>\n" +
                "        <adminDown>false</adminDown>\n" +
                "        <linkType>TE_TUNNEL</linkType>\n" +
                "        <createType>SESS_STATIC</createType>\n" +
                "        <tunnelName>Tunnel1</tunnelName>\n" +
                "        <teBackup>false</teBackup>\n" +
                "        <processPst>false</processPst>\n" +
                "        <pis>false</pis>\n" +
                "        <pisSubIf>false</pisSubIf>\n" +
                "        <useDefaultIp>false</useDefaultIp>\n" +
                "        <addrType>IPV4</addrType>\n" +
                "        <autoCalc>false</autoCalc>\n" +
                "        <pwSecondary>false</pwSecondary>\n" +
                "        <isSetTrackIf>false</isSetTrackIf>\n" +
                "        <oneArmEcho>false</oneArmEcho>\n" +
                "        <bundleMode>-</bundleMode>\n" +
                "        <pisNoImpact>false</pisNoImpact>\n" +
                "        <bfdSessRunning>\n" +
                "          <udpDstPort>3784</udpDstPort>\n" +
                "          <detectMode>ASYNC_WITHOUT_ECHO</detectMode>\n" +
                "          <sessState>DOWN</sessState>\n" +
                "          <localDiscr>3</localDiscr>\n" +
                "          <ttl>1</ttl>\n" +
                "          <notUpReason>Board-selecting-failed</notUpReason>\n" +
                "          <localDiag>NONE</localDiag>\n" +
                "          <remoteDiscr>3</remoteDiscr>\n" +
                "          <minTxInt>3</minTxInt>\n" +
                "          <minRxInt>22</minRxInt>\n" +
                "        </bfdSessRunning>\n" +
                "      </bfdCfgSession>\n" +
                "    </bfdCfgSessions>\n" +
                "  </bfd>\n" +
                "</data>";
    }
}
