package cn.org.upbnc.xmlcompare;

public class EbgpUtils {
    public static String running(){
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<data xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n" +
                "  <bgp xmlns=\"http://www.huawei.com/netconf/vrp/huawei-bgp\">\n" +
                "    <bgpcomm>\n" +
                "      <bgpVrfs>\n" +
                "        <bgpVrf>\n" +
                "          <vrfName>VPN-test</vrfName>\n" +
                "          <defaultAfType>ipv4uni</defaultAfType>\n" +
                "          <vrfRidAutoSel>false</vrfRidAutoSel>\n" +
                "          <effectRouterId>1.1.1.1</effectRouterId>\n" +
                "          <vrfSession>false</vrfSession>\n" +
                "          <bgpPeers>\n" +
                "            <bgpPeer>\n" +
                "              <peerAddr>192.168.1.4</peerAddr>\n" +
                "              <remoteAs>44</remoteAs>\n" +
                "              <routeRefresh>true</routeRefresh>\n" +
                "              <fourByteAs>true</fourByteAs>\n" +
                "              <conventional>false</conventional>\n" +
                "              <ebgpMaxHop>1</ebgpMaxHop>\n" +
                "              <isIgnore>false</isIgnore>\n" +
                "              <connectMode>null</connectMode>\n" +
                "              <isLogChange>true</isLogChange>\n" +
                "              <pswdType>null</pswdType>\n" +
                "              <keepAliveTime>60</keepAliveTime>\n" +
                "              <holdTime>180</holdTime>\n" +
                "              <pathMTUD>false</pathMTUD>\n" +
                "              <dualAs>false</dualAs>\n" +
                "              <trackingEnable>false</trackingEnable>\n" +
                "              <trackDelayTime>0</trackDelayTime>\n" +
                "              <connRetryTime>32</connRetryTime>\n" +
                "              <prependGlobalAs>false</prependGlobalAs>\n" +
                "              <prependFakeAs>false</prependFakeAs>\n" +
                "              <minHoldTime>0</minHoldTime>\n" +
                "              <checkFirstAs>default</checkFirstAs>\n" +
                "            </bgpPeer>\n" +
                "          </bgpPeers>\n" +
                "          <bgpVrfAFs>\n" +
                "            <bgpVrfAF>\n" +
                "              <afType>ipv4uni</afType>\n" +
                "              <asPathNeglect>false</asPathNeglect>\n" +
                "              <medNoneAsMaximum>false</medNoneAsMaximum>\n" +
                "              <alwaysCompareMed>false</alwaysCompareMed>\n" +
                "              <defaultLocalPref>100</defaultLocalPref>\n" +
                "              <defaultMed>0</defaultMed>\n" +
                "              <defaultRtImportEnable>false</defaultRtImportEnable>\n" +
                "              <maximumLoadBalance>1</maximumLoadBalance>\n" +
                "              <preferenceExternal>24</preferenceExternal>\n" +
                "              <preferenceInternal>24</preferenceInternal>\n" +
                "              <preferenceLocal>24</preferenceLocal>\n" +
                "              <reflectBetweenClient>true</reflectBetweenClient>\n" +
                "              <summaryAutomatic>false</summaryAutomatic>\n" +
                "              <routerIdNeglect>false</routerIdNeglect>\n" +
                "              <igpMetricIgnore>false</igpMetricIgnore>\n" +
                "              <autoFrrEnable>false</autoFrrEnable>\n" +
                "              <determinMed>false</determinMed>\n" +
                "              <ebgpIfSensitive>true</ebgpIfSensitive>\n" +
                "              <maxLoadEbgpNum>1</maxLoadEbgpNum>\n" +
                "              <maxLoadIbgpNum>1</maxLoadIbgpNum>\n" +
                "              <ecmpNexthopChanged>false</ecmpNexthopChanged>\n" +
                "              <eibgpEcmpNexthopChanged>false</eibgpEcmpNexthopChanged>\n" +
                "              <ebgpEcmpNexthopChanged>false</ebgpEcmpNexthopChanged>\n" +
                "              <ibgpEcmpNexthopChanged>false</ibgpEcmpNexthopChanged>\n" +
                "              <reflectChgPath>false</reflectChgPath>\n" +
                "              <vrfRidAutoSel>false</vrfRidAutoSel>\n" +
                "              <enBestRtBitErrDetection>false</enBestRtBitErrDetection>\n" +
                "              <activeRouteAdvertise>false</activeRouteAdvertise>\n" +
                "              <routeSelDelay>0</routeSelDelay>\n" +
                "              <originAsValid>false</originAsValid>\n" +
                "              <allowInvalidAs>false</allowInvalidAs>\n" +
                "              <originAsValidEnable>false</originAsValidEnable>\n" +
                "              <policyExtCommEnable>false</policyExtCommEnable>\n" +
                "              <supernetUniAdv>false</supernetUniAdv>\n" +
                "              <supernetLabelAdv>true</supernetLabelAdv>\n" +
                "              <loadBalancingIgpMetricIgnore>false</loadBalancingIgpMetricIgnore>\n" +
                "              <loadBalancingEibgp>false</loadBalancingEibgp>\n" +
                "              <loadBalancingAsPathIgnore>false</loadBalancingAsPathIgnore>\n" +
                "              <loadBalancingAsPathRelax>false</loadBalancingAsPathRelax>\n" +
                "              <originatorPrior>false</originatorPrior>\n" +
                "              <relayDelayEnable>true</relayDelayEnable>\n" +
                "              <medPlusIgp>false</medPlusIgp>\n" +
                "              <medMultiplier>1</medMultiplier>\n" +
                "              <igpMultiplier>1</igpMultiplier>\n" +
                "              <vrfImportnhpinvariable>false</vrfImportnhpinvariable>\n" +
                "              <slowPeerDet>true</slowPeerDet>\n" +
                "              <slowPeerThVal>300</slowPeerThVal>\n" +
                "              <slowPeerAbDet>true</slowPeerAbDet>\n" +
                "              <slowPeerAbThVal>9</slowPeerAbThVal>\n" +
                "              <aigp>false</aigp>\n" +
                "              <autoSid>false</autoSid>\n" +
                "              <srIpv6Mode>null</srIpv6Mode>\n" +
                "              <rpdPolicyChangeDelay>30</rpdPolicyChangeDelay>\n" +
                "              <advRouteMode>all</advRouteMode>\n" +
                "              <attrSetEnable>false</attrSetEnable>\n" +
                "              <evpnBgpAFConfig/>\n" +
                "              <vrfAFBriefInfo>\n" +
                "                <peerNum>1</peerNum>\n" +
                "                <routeNum>0</routeNum>\n" +
                "                <rdNum>0</rdNum>\n" +
                "              </vrfAFBriefInfo>\n" +
                "              <bgpRtStaticsInfo>\n" +
                "                <advRmTotalNum>0</advRmTotalNum>\n" +
                "                <activeRtNum>0</activeRtNum>\n" +
                "                <bestRtNum>0</bestRtNum>\n" +
                "                <addPathRtNum>0</addPathRtNum>\n" +
                "                <advBestRtNum>0</advBestRtNum>\n" +
                "                <cidrRtNum>0</cidrRtNum>\n" +
                "                <cmmyRtNum>0</cmmyRtNum>\n" +
                "                <diffOriAsRtNum>0</diffOriAsRtNum>\n" +
                "                <dampRtNum>0</dampRtNum>\n" +
                "                <ngType1RtNum>0</ngType1RtNum>\n" +
                "                <ngType2RtNum>0</ngType2RtNum>\n" +
                "                <ngType3RtNum>0</ngType3RtNum>\n" +
                "                <ngType4RtNum>0</ngType4RtNum>\n" +
                "                <ngType5RtNum>0</ngType5RtNum>\n" +
                "                <ngType6RtNum>0</ngType6RtNum>\n" +
                "                <ngType7RtNum>0</ngType7RtNum>\n" +
                "                <vrfRtNum>0</vrfRtNum>\n" +
                "                <lsNodeRtNum>0</lsNodeRtNum>\n" +
                "                <lsLinkRtNum>0</lsLinkRtNum>\n" +
                "                <lsIpv4PrefixRtNum>0</lsIpv4PrefixRtNum>\n" +
                "                <lsIpv6PrefixRtNum>0</lsIpv6PrefixRtNum>\n" +
                "              </bgpRtStaticsInfo>\n" +
                "              <peerAFs>\n" +
                "                <peerAF>\n" +
                "                  <remoteAddress>192.168.1.4</remoteAddress>\n" +
                "                  <advertiseCommunity>true</advertiseCommunity>\n" +
                "                  <advertiseExtCommunity>false</advertiseExtCommunity>\n" +
                "                  <discardExtCommunity>false</discardExtCommunity>\n" +
                "                  <allowAsLoopEnable>false</allowAsLoopEnable>\n" +
                "                  <defaultRtAdvEnable>false</defaultRtAdvEnable>\n" +
                "                  <defaultRtMatchMode>null</defaultRtMatchMode>\n" +
                "                  <keepAllRoutes>false</keepAllRoutes>\n" +
                "                  <nextHopConfigure>null</nextHopConfigure>\n" +
                "                  <preferredValue>0</preferredValue>\n" +
                "                  <publicAsOnly>false</publicAsOnly>\n" +
                "                  <rtUpdtInterval>30</rtUpdtInterval>\n" +
                "                  <reflectClient>false</reflectClient>\n" +
                "                  <substituteAsEnable>false</substituteAsEnable>\n" +
                "                  <importRtPolicyName>1</importRtPolicyName>\n" +
                "                  <exportRtPolicyName>2</exportRtPolicyName>\n" +
                "                  <labelRouteCapability>false</labelRouteCapability>\n" +
                "                  <checkTunnelReachable>false</checkTunnelReachable>\n" +
                "                  <originAsValid>false</originAsValid>\n" +
                "                  <publicAsOnlyForce>false</publicAsOnlyForce>\n" +
                "                  <publicAsOnlyLimited>false</publicAsOnlyLimited>\n" +
                "                  <publicAsOnlyReplace>false</publicAsOnlyReplace>\n" +
                "                  <publicAsOnlySkipPeerAs>false</publicAsOnlySkipPeerAs>\n" +
                "                  <loadBalancingEnable>false</loadBalancingEnable>\n" +
                "                  <loadBalancingIgnoreAs>false</loadBalancingIgnoreAs>\n" +
                "                  <loadBalancingRelaxAs>false</loadBalancingRelaxAs>\n" +
                "                  <upgCfgIndependent>default</upgCfgIndependent>\n" +
                "                  <upgEffectIndependent>false</upgEffectIndependent>\n" +
                "                  <statisticsInfo>\n" +
                "                    <recvNLRINum>0</recvNLRINum>\n" +
                "                    <recvUNLRINum>0</recvUNLRINum>\n" +
                "                    <prePlyRouteNum>0</prePlyRouteNum>\n" +
                "                    <postPlyRouteNum>0</postPlyRouteNum>\n" +
                "                    <bestRouteNum>0</bestRouteNum>\n" +
                "                    <rejectedRtNum>0</rejectedRtNum>\n" +
                "                    <asPathLoopRtNum>0</asPathLoopRtNum>\n" +
                "                    <asConfLoopRtNum>0</asConfLoopRtNum>\n" +
                "                    <cluLoopRtNum>0</cluLoopRtNum>\n" +
                "                    <invalOrigRtNum>0</invalOrigRtNum>\n" +
                "                  </statisticsInfo>\n" +
                "                  <peerInfo>\n" +
                "                    <peerType>ebgp</peerType>\n" +
                "                    <version>4</version>\n" +
                "                    <remoteRouterId>0.0.0.0</remoteRouterId>\n" +
                "                    <bgpCurState>idle</bgpCurState>\n" +
                "                    <localPort>0</localPort>\n" +
                "                    <remotePort>0</remotePort>\n" +
                "                    <currentEvent>IHTimerExpired</currentEvent>\n" +
                "                    <bgpLastState>idle</bgpLastState>\n" +
                "                    <messageSent>0</messageSent>\n" +
                "                    <messageReceived>0</messageReceived>\n" +
                "                    <outQueue>0</outQueue>\n" +
                "                    <revHoldTime>0</revHoldTime>\n" +
                "                    <negoHoldTime>0</negoHoldTime>\n" +
                "                    <negoKeepAliveTime>0</negoKeepAliveTime>\n" +
                "                    <revUpdateCount>0</revUpdateCount>\n" +
                "                    <revOpenCount>0</revOpenCount>\n" +
                "                    <revKeepAliveCount>0</revKeepAliveCount>\n" +
                "                    <revNotificationCount>0</revNotificationCount>\n" +
                "                    <revRouteRefreshCount>0</revRouteRefreshCount>\n" +
                "                    <sentUpdateCount>0</sentUpdateCount>\n" +
                "                    <sentOpenCount>0</sentOpenCount>\n" +
                "                    <sentKeepAliveCount>0</sentKeepAliveCount>\n" +
                "                    <sentNotificationCount>0</sentNotificationCount>\n" +
                "                    <sentRouteRefreshCount>0</sentRouteRefreshCount>\n" +
                "                    <sendGRCapability>false</sendGRCapability>\n" +
                "                    <revRefreshCapability>false</revRefreshCapability>\n" +
                "                    <revFourByteASCapability>false</revFourByteASCapability>\n" +
                "                    <revSupportMPCapability>false</revSupportMPCapability>\n" +
                "                    <revGRCapability>false</revGRCapability>\n" +
                "                    <prefRecv>0</prefRecv>\n" +
                "                    <activePrefRecv>0</activePrefRecv>\n" +
                "                    <prefAdvertised>0</prefAdvertised>\n" +
                "                    <peerRpdCapability>null</peerRpdCapability>\n" +
                "                    <localRpdCapability>null</localRpdCapability>\n" +
                "                    <negotiatedRpdCapability>null</negotiatedRpdCapability>\n" +
                "                    <checkFirstAs>enable</checkFirstAs>\n" +
                "                    <peerExtNhpCap>false</peerExtNhpCap>\n" +
                "                  </peerInfo>\n" +
                "                </peerAF>\n" +
                "              </peerAFs>\n" +
                "            </bgpVrfAF>\n" +
                "          </bgpVrfAFs>\n" +
                "        </bgpVrf>\n" +
                "      </bgpVrfs>\n" +
                "    </bgpcomm>\n" +
                "  </bgp>\n" +
                "</data>";
    }

    public static String add(){
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<data xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n" +
                "  <bgp xmlns=\"http://www.huawei.com/netconf/vrp/huawei-bgp\">\n" +
                "    <bgpcomm>\n" +
                "      <bgpVrfs>\n" +
                "        <bgpVrf>\n" +
                "          <vrfName>VPN-test</vrfName>\n" +
                "          <defaultAfType>ipv4uni</defaultAfType>\n" +
                "          <vrfRidAutoSel>false</vrfRidAutoSel>\n" +
                "          <effectRouterId>1.1.1.1</effectRouterId>\n" +
                "          <vrfSession>false</vrfSession>\n" +
                "          <bgpPeers>\n" +
                "            <bgpPeer>\n" +
                "              <peerAddr>192.168.1.4</peerAddr>\n" +
                "              <remoteAs>44</remoteAs>\n" +
                "              <routeRefresh>true</routeRefresh>\n" +
                "              <fourByteAs>true</fourByteAs>\n" +
                "              <conventional>false</conventional>\n" +
                "              <ebgpMaxHop>1</ebgpMaxHop>\n" +
                "              <isIgnore>false</isIgnore>\n" +
                "              <connectMode>null</connectMode>\n" +
                "              <isLogChange>true</isLogChange>\n" +
                "              <pswdType>null</pswdType>\n" +
                "              <keepAliveTime>60</keepAliveTime>\n" +
                "              <holdTime>180</holdTime>\n" +
                "              <pathMTUD>false</pathMTUD>\n" +
                "              <dualAs>false</dualAs>\n" +
                "              <trackingEnable>false</trackingEnable>\n" +
                "              <trackDelayTime>0</trackDelayTime>\n" +
                "              <connRetryTime>32</connRetryTime>\n" +
                "              <prependGlobalAs>false</prependGlobalAs>\n" +
                "              <prependFakeAs>false</prependFakeAs>\n" +
                "              <minHoldTime>0</minHoldTime>\n" +
                "              <checkFirstAs>default</checkFirstAs>\n" +
                "            </bgpPeer>\n" +
                "          </bgpPeers>\n" +
                "          <bgpVrfAFs>\n" +
                "            <bgpVrfAF>\n" +
                "              <afType>ipv4uni</afType>\n" +
                "              <asPathNeglect>false</asPathNeglect>\n" +
                "              <medNoneAsMaximum>false</medNoneAsMaximum>\n" +
                "              <alwaysCompareMed>false</alwaysCompareMed>\n" +
                "              <defaultLocalPref>100</defaultLocalPref>\n" +
                "              <defaultMed>0</defaultMed>\n" +
                "              <defaultRtImportEnable>false</defaultRtImportEnable>\n" +
                "              <maximumLoadBalance>1</maximumLoadBalance>\n" +
                "              <preferenceExternal>24</preferenceExternal>\n" +
                "              <preferenceInternal>24</preferenceInternal>\n" +
                "              <preferenceLocal>24</preferenceLocal>\n" +
                "              <reflectBetweenClient>true</reflectBetweenClient>\n" +
                "              <summaryAutomatic>false</summaryAutomatic>\n" +
                "              <routerIdNeglect>false</routerIdNeglect>\n" +
                "              <igpMetricIgnore>false</igpMetricIgnore>\n" +
                "              <autoFrrEnable>false</autoFrrEnable>\n" +
                "              <determinMed>false</determinMed>\n" +
                "              <ebgpIfSensitive>true</ebgpIfSensitive>\n" +
                "              <maxLoadEbgpNum>1</maxLoadEbgpNum>\n" +
                "              <maxLoadIbgpNum>1</maxLoadIbgpNum>\n" +
                "              <ecmpNexthopChanged>false</ecmpNexthopChanged>\n" +
                "              <eibgpEcmpNexthopChanged>false</eibgpEcmpNexthopChanged>\n" +
                "              <ebgpEcmpNexthopChanged>false</ebgpEcmpNexthopChanged>\n" +
                "              <ibgpEcmpNexthopChanged>false</ibgpEcmpNexthopChanged>\n" +
                "              <reflectChgPath>false</reflectChgPath>\n" +
                "              <vrfRidAutoSel>false</vrfRidAutoSel>\n" +
                "              <enBestRtBitErrDetection>false</enBestRtBitErrDetection>\n" +
                "              <activeRouteAdvertise>false</activeRouteAdvertise>\n" +
                "              <routeSelDelay>0</routeSelDelay>\n" +
                "              <originAsValid>false</originAsValid>\n" +
                "              <allowInvalidAs>false</allowInvalidAs>\n" +
                "              <originAsValidEnable>false</originAsValidEnable>\n" +
                "              <policyExtCommEnable>false</policyExtCommEnable>\n" +
                "              <supernetUniAdv>false</supernetUniAdv>\n" +
                "              <supernetLabelAdv>true</supernetLabelAdv>\n" +
                "              <loadBalancingIgpMetricIgnore>false</loadBalancingIgpMetricIgnore>\n" +
                "              <loadBalancingEibgp>false</loadBalancingEibgp>\n" +
                "              <loadBalancingAsPathIgnore>false</loadBalancingAsPathIgnore>\n" +
                "              <loadBalancingAsPathRelax>false</loadBalancingAsPathRelax>\n" +
                "              <originatorPrior>false</originatorPrior>\n" +
                "              <relayDelayEnable>true</relayDelayEnable>\n" +
                "              <medPlusIgp>false</medPlusIgp>\n" +
                "              <medMultiplier>1</medMultiplier>\n" +
                "              <igpMultiplier>1</igpMultiplier>\n" +
                "              <vrfImportnhpinvariable>false</vrfImportnhpinvariable>\n" +
                "              <slowPeerDet>true</slowPeerDet>\n" +
                "              <slowPeerThVal>300</slowPeerThVal>\n" +
                "              <slowPeerAbDet>true</slowPeerAbDet>\n" +
                "              <slowPeerAbThVal>9</slowPeerAbThVal>\n" +
                "              <aigp>false</aigp>\n" +
                "              <autoSid>false</autoSid>\n" +
                "              <srIpv6Mode>null</srIpv6Mode>\n" +
                "              <rpdPolicyChangeDelay>30</rpdPolicyChangeDelay>\n" +
                "              <advRouteMode>all</advRouteMode>\n" +
                "              <attrSetEnable>false</attrSetEnable>\n" +
                "              <evpnBgpAFConfig/>\n" +
                "              <vrfAFBriefInfo>\n" +
                "                <peerNum>1</peerNum>\n" +
                "                <routeNum>0</routeNum>\n" +
                "                <rdNum>0</rdNum>\n" +
                "              </vrfAFBriefInfo>\n" +
                "              <bgpRtStaticsInfo>\n" +
                "                <advRmTotalNum>0</advRmTotalNum>\n" +
                "                <activeRtNum>0</activeRtNum>\n" +
                "                <bestRtNum>0</bestRtNum>\n" +
                "                <addPathRtNum>0</addPathRtNum>\n" +
                "                <advBestRtNum>0</advBestRtNum>\n" +
                "                <cidrRtNum>0</cidrRtNum>\n" +
                "                <cmmyRtNum>0</cmmyRtNum>\n" +
                "                <diffOriAsRtNum>0</diffOriAsRtNum>\n" +
                "                <dampRtNum>0</dampRtNum>\n" +
                "                <ngType1RtNum>0</ngType1RtNum>\n" +
                "                <ngType2RtNum>0</ngType2RtNum>\n" +
                "                <ngType3RtNum>0</ngType3RtNum>\n" +
                "                <ngType4RtNum>0</ngType4RtNum>\n" +
                "                <ngType5RtNum>0</ngType5RtNum>\n" +
                "                <ngType6RtNum>0</ngType6RtNum>\n" +
                "                <ngType7RtNum>0</ngType7RtNum>\n" +
                "                <vrfRtNum>0</vrfRtNum>\n" +
                "                <lsNodeRtNum>0</lsNodeRtNum>\n" +
                "                <lsLinkRtNum>0</lsLinkRtNum>\n" +
                "                <lsIpv4PrefixRtNum>0</lsIpv4PrefixRtNum>\n" +
                "                <lsIpv6PrefixRtNum>0</lsIpv6PrefixRtNum>\n" +
                "              </bgpRtStaticsInfo>\n" +
                "              <peerAFs>\n" +
                "                <peerAF>\n" +
                "                  <remoteAddress>192.168.1.4</remoteAddress>\n" +
                "                  <advertiseCommunity>true</advertiseCommunity>\n" +
                "                  <advertiseExtCommunity>false</advertiseExtCommunity>\n" +
                "                  <discardExtCommunity>false</discardExtCommunity>\n" +
                "                  <allowAsLoopEnable>false</allowAsLoopEnable>\n" +
                "                  <defaultRtAdvEnable>false</defaultRtAdvEnable>\n" +
                "                  <defaultRtMatchMode>null</defaultRtMatchMode>\n" +
                "                  <keepAllRoutes>false</keepAllRoutes>\n" +
                "                  <nextHopConfigure>null</nextHopConfigure>\n" +
                "                  <preferredValue>0</preferredValue>\n" +
                "                  <publicAsOnly>false</publicAsOnly>\n" +
                "                  <rtUpdtInterval>30</rtUpdtInterval>\n" +
                "                  <reflectClient>false</reflectClient>\n" +
                "                  <substituteAsEnable>false</substituteAsEnable>\n" +
                "                  <importRtPolicyName>1</importRtPolicyName>\n" +
                "                  <exportRtPolicyName>2</exportRtPolicyName>\n" +
                "                  <labelRouteCapability>false</labelRouteCapability>\n" +
                "                  <checkTunnelReachable>false</checkTunnelReachable>\n" +
                "                  <originAsValid>false</originAsValid>\n" +
                "                  <publicAsOnlyForce>false</publicAsOnlyForce>\n" +
                "                  <publicAsOnlyLimited>false</publicAsOnlyLimited>\n" +
                "                  <publicAsOnlyReplace>false</publicAsOnlyReplace>\n" +
                "                  <publicAsOnlySkipPeerAs>false</publicAsOnlySkipPeerAs>\n" +
                "                  <loadBalancingEnable>false</loadBalancingEnable>\n" +
                "                  <loadBalancingIgnoreAs>false</loadBalancingIgnoreAs>\n" +
                "                  <loadBalancingRelaxAs>false</loadBalancingRelaxAs>\n" +
                "                  <upgCfgIndependent>default</upgCfgIndependent>\n" +
                "                  <upgEffectIndependent>false</upgEffectIndependent>\n" +
                "                  <statisticsInfo>\n" +
                "                    <recvNLRINum>0</recvNLRINum>\n" +
                "                    <recvUNLRINum>0</recvUNLRINum>\n" +
                "                    <prePlyRouteNum>0</prePlyRouteNum>\n" +
                "                    <postPlyRouteNum>0</postPlyRouteNum>\n" +
                "                    <bestRouteNum>0</bestRouteNum>\n" +
                "                    <rejectedRtNum>0</rejectedRtNum>\n" +
                "                    <asPathLoopRtNum>0</asPathLoopRtNum>\n" +
                "                    <asConfLoopRtNum>0</asConfLoopRtNum>\n" +
                "                    <cluLoopRtNum>0</cluLoopRtNum>\n" +
                "                    <invalOrigRtNum>0</invalOrigRtNum>\n" +
                "                  </statisticsInfo>\n" +
                "                  <peerInfo>\n" +
                "                    <peerType>ebgp</peerType>\n" +
                "                    <version>4</version>\n" +
                "                    <remoteRouterId>0.0.0.0</remoteRouterId>\n" +
                "                    <bgpCurState>idle</bgpCurState>\n" +
                "                    <localPort>0</localPort>\n" +
                "                    <remotePort>0</remotePort>\n" +
                "                    <currentEvent>IHTimerExpired</currentEvent>\n" +
                "                    <bgpLastState>idle</bgpLastState>\n" +
                "                    <messageSent>0</messageSent>\n" +
                "                    <messageReceived>0</messageReceived>\n" +
                "                    <outQueue>0</outQueue>\n" +
                "                    <revHoldTime>0</revHoldTime>\n" +
                "                    <negoHoldTime>0</negoHoldTime>\n" +
                "                    <negoKeepAliveTime>0</negoKeepAliveTime>\n" +
                "                    <revUpdateCount>0</revUpdateCount>\n" +
                "                    <revOpenCount>0</revOpenCount>\n" +
                "                    <revKeepAliveCount>0</revKeepAliveCount>\n" +
                "                    <revNotificationCount>0</revNotificationCount>\n" +
                "                    <revRouteRefreshCount>0</revRouteRefreshCount>\n" +
                "                    <sentUpdateCount>0</sentUpdateCount>\n" +
                "                    <sentOpenCount>0</sentOpenCount>\n" +
                "                    <sentKeepAliveCount>0</sentKeepAliveCount>\n" +
                "                    <sentNotificationCount>0</sentNotificationCount>\n" +
                "                    <sentRouteRefreshCount>0</sentRouteRefreshCount>\n" +
                "                    <sendGRCapability>false</sendGRCapability>\n" +
                "                    <revRefreshCapability>false</revRefreshCapability>\n" +
                "                    <revFourByteASCapability>false</revFourByteASCapability>\n" +
                "                    <revSupportMPCapability>false</revSupportMPCapability>\n" +
                "                    <revGRCapability>false</revGRCapability>\n" +
                "                    <prefRecv>0</prefRecv>\n" +
                "                    <activePrefRecv>0</activePrefRecv>\n" +
                "                    <prefAdvertised>0</prefAdvertised>\n" +
                "                    <peerRpdCapability>null</peerRpdCapability>\n" +
                "                    <localRpdCapability>null</localRpdCapability>\n" +
                "                    <negotiatedRpdCapability>null</negotiatedRpdCapability>\n" +
                "                    <checkFirstAs>enable</checkFirstAs>\n" +
                "                    <peerExtNhpCap>false</peerExtNhpCap>\n" +
                "                  </peerInfo>\n" +
                "                </peerAF>\n" +
                "              </peerAFs>\n" +
                "            </bgpVrfAF>\n" +
                "          </bgpVrfAFs>\n" +
                "        </bgpVrf>\n" +
                "        <bgpVrf>\n" +
                "          <vrfName>VPN-test1</vrfName>\n" +
                "          <defaultAfType>ipv4uni</defaultAfType>\n" +
                "          <vrfRidAutoSel>false</vrfRidAutoSel>\n" +
                "          <effectRouterId>1.1.1.1</effectRouterId>\n" +
                "          <vrfSession>false</vrfSession>\n" +
                "          <bgpPeers>\n" +
                "            <bgpPeer>\n" +
                "              <peerAddr>192.168.1.4</peerAddr>\n" +
                "              <remoteAs>44</remoteAs>\n" +
                "              <routeRefresh>true</routeRefresh>\n" +
                "              <fourByteAs>true</fourByteAs>\n" +
                "              <conventional>false</conventional>\n" +
                "              <ebgpMaxHop>1</ebgpMaxHop>\n" +
                "              <isIgnore>false</isIgnore>\n" +
                "              <connectMode>null</connectMode>\n" +
                "              <isLogChange>true</isLogChange>\n" +
                "              <pswdType>null</pswdType>\n" +
                "              <keepAliveTime>60</keepAliveTime>\n" +
                "              <holdTime>180</holdTime>\n" +
                "              <pathMTUD>false</pathMTUD>\n" +
                "              <dualAs>false</dualAs>\n" +
                "              <trackingEnable>false</trackingEnable>\n" +
                "              <trackDelayTime>0</trackDelayTime>\n" +
                "              <connRetryTime>32</connRetryTime>\n" +
                "              <prependGlobalAs>false</prependGlobalAs>\n" +
                "              <prependFakeAs>false</prependFakeAs>\n" +
                "              <minHoldTime>0</minHoldTime>\n" +
                "              <checkFirstAs>default</checkFirstAs>\n" +
                "            </bgpPeer>\n" +
                "          </bgpPeers>\n" +
                "          <bgpVrfAFs>\n" +
                "            <bgpVrfAF>\n" +
                "              <afType>ipv4uni</afType>\n" +
                "              <asPathNeglect>false</asPathNeglect>\n" +
                "              <medNoneAsMaximum>false</medNoneAsMaximum>\n" +
                "              <alwaysCompareMed>false</alwaysCompareMed>\n" +
                "              <defaultLocalPref>100</defaultLocalPref>\n" +
                "              <defaultMed>0</defaultMed>\n" +
                "              <defaultRtImportEnable>false</defaultRtImportEnable>\n" +
                "              <maximumLoadBalance>1</maximumLoadBalance>\n" +
                "              <preferenceExternal>24</preferenceExternal>\n" +
                "              <preferenceInternal>24</preferenceInternal>\n" +
                "              <preferenceLocal>24</preferenceLocal>\n" +
                "              <reflectBetweenClient>true</reflectBetweenClient>\n" +
                "              <summaryAutomatic>false</summaryAutomatic>\n" +
                "              <routerIdNeglect>false</routerIdNeglect>\n" +
                "              <igpMetricIgnore>false</igpMetricIgnore>\n" +
                "              <autoFrrEnable>false</autoFrrEnable>\n" +
                "              <determinMed>false</determinMed>\n" +
                "              <ebgpIfSensitive>true</ebgpIfSensitive>\n" +
                "              <maxLoadEbgpNum>1</maxLoadEbgpNum>\n" +
                "              <maxLoadIbgpNum>1</maxLoadIbgpNum>\n" +
                "              <ecmpNexthopChanged>false</ecmpNexthopChanged>\n" +
                "              <eibgpEcmpNexthopChanged>false</eibgpEcmpNexthopChanged>\n" +
                "              <ebgpEcmpNexthopChanged>false</ebgpEcmpNexthopChanged>\n" +
                "              <ibgpEcmpNexthopChanged>false</ibgpEcmpNexthopChanged>\n" +
                "              <reflectChgPath>false</reflectChgPath>\n" +
                "              <vrfRidAutoSel>false</vrfRidAutoSel>\n" +
                "              <enBestRtBitErrDetection>false</enBestRtBitErrDetection>\n" +
                "              <activeRouteAdvertise>false</activeRouteAdvertise>\n" +
                "              <routeSelDelay>0</routeSelDelay>\n" +
                "              <originAsValid>false</originAsValid>\n" +
                "              <allowInvalidAs>false</allowInvalidAs>\n" +
                "              <originAsValidEnable>false</originAsValidEnable>\n" +
                "              <policyExtCommEnable>false</policyExtCommEnable>\n" +
                "              <supernetUniAdv>false</supernetUniAdv>\n" +
                "              <supernetLabelAdv>true</supernetLabelAdv>\n" +
                "              <loadBalancingIgpMetricIgnore>false</loadBalancingIgpMetricIgnore>\n" +
                "              <loadBalancingEibgp>false</loadBalancingEibgp>\n" +
                "              <loadBalancingAsPathIgnore>false</loadBalancingAsPathIgnore>\n" +
                "              <loadBalancingAsPathRelax>false</loadBalancingAsPathRelax>\n" +
                "              <originatorPrior>false</originatorPrior>\n" +
                "              <relayDelayEnable>true</relayDelayEnable>\n" +
                "              <medPlusIgp>false</medPlusIgp>\n" +
                "              <medMultiplier>1</medMultiplier>\n" +
                "              <igpMultiplier>1</igpMultiplier>\n" +
                "              <vrfImportnhpinvariable>false</vrfImportnhpinvariable>\n" +
                "              <slowPeerDet>true</slowPeerDet>\n" +
                "              <slowPeerThVal>300</slowPeerThVal>\n" +
                "              <slowPeerAbDet>true</slowPeerAbDet>\n" +
                "              <slowPeerAbThVal>9</slowPeerAbThVal>\n" +
                "              <aigp>false</aigp>\n" +
                "              <autoSid>false</autoSid>\n" +
                "              <srIpv6Mode>null</srIpv6Mode>\n" +
                "              <rpdPolicyChangeDelay>30</rpdPolicyChangeDelay>\n" +
                "              <advRouteMode>all</advRouteMode>\n" +
                "              <attrSetEnable>false</attrSetEnable>\n" +
                "              <evpnBgpAFConfig/>\n" +
                "              <vrfAFBriefInfo>\n" +
                "                <peerNum>1</peerNum>\n" +
                "                <routeNum>0</routeNum>\n" +
                "                <rdNum>0</rdNum>\n" +
                "              </vrfAFBriefInfo>\n" +
                "              <bgpRtStaticsInfo>\n" +
                "                <advRmTotalNum>0</advRmTotalNum>\n" +
                "                <activeRtNum>0</activeRtNum>\n" +
                "                <bestRtNum>0</bestRtNum>\n" +
                "                <addPathRtNum>0</addPathRtNum>\n" +
                "                <advBestRtNum>0</advBestRtNum>\n" +
                "                <cidrRtNum>0</cidrRtNum>\n" +
                "                <cmmyRtNum>0</cmmyRtNum>\n" +
                "                <diffOriAsRtNum>0</diffOriAsRtNum>\n" +
                "                <dampRtNum>0</dampRtNum>\n" +
                "                <ngType1RtNum>0</ngType1RtNum>\n" +
                "                <ngType2RtNum>0</ngType2RtNum>\n" +
                "                <ngType3RtNum>0</ngType3RtNum>\n" +
                "                <ngType4RtNum>0</ngType4RtNum>\n" +
                "                <ngType5RtNum>0</ngType5RtNum>\n" +
                "                <ngType6RtNum>0</ngType6RtNum>\n" +
                "                <ngType7RtNum>0</ngType7RtNum>\n" +
                "                <vrfRtNum>0</vrfRtNum>\n" +
                "                <lsNodeRtNum>0</lsNodeRtNum>\n" +
                "                <lsLinkRtNum>0</lsLinkRtNum>\n" +
                "                <lsIpv4PrefixRtNum>0</lsIpv4PrefixRtNum>\n" +
                "                <lsIpv6PrefixRtNum>0</lsIpv6PrefixRtNum>\n" +
                "              </bgpRtStaticsInfo>\n" +
                "              <peerAFs>\n" +
                "                <peerAF>\n" +
                "                  <remoteAddress>192.168.1.4</remoteAddress>\n" +
                "                  <advertiseCommunity>true</advertiseCommunity>\n" +
                "                  <advertiseExtCommunity>false</advertiseExtCommunity>\n" +
                "                  <discardExtCommunity>false</discardExtCommunity>\n" +
                "                  <allowAsLoopEnable>false</allowAsLoopEnable>\n" +
                "                  <defaultRtAdvEnable>false</defaultRtAdvEnable>\n" +
                "                  <defaultRtMatchMode>null</defaultRtMatchMode>\n" +
                "                  <keepAllRoutes>false</keepAllRoutes>\n" +
                "                  <nextHopConfigure>null</nextHopConfigure>\n" +
                "                  <preferredValue>0</preferredValue>\n" +
                "                  <publicAsOnly>false</publicAsOnly>\n" +
                "                  <rtUpdtInterval>30</rtUpdtInterval>\n" +
                "                  <reflectClient>false</reflectClient>\n" +
                "                  <substituteAsEnable>false</substituteAsEnable>\n" +
                "                  <importRtPolicyName>1</importRtPolicyName>\n" +
                "                  <exportRtPolicyName>2</exportRtPolicyName>\n" +
                "                  <labelRouteCapability>false</labelRouteCapability>\n" +
                "                  <checkTunnelReachable>false</checkTunnelReachable>\n" +
                "                  <originAsValid>false</originAsValid>\n" +
                "                  <publicAsOnlyForce>false</publicAsOnlyForce>\n" +
                "                  <publicAsOnlyLimited>false</publicAsOnlyLimited>\n" +
                "                  <publicAsOnlyReplace>false</publicAsOnlyReplace>\n" +
                "                  <publicAsOnlySkipPeerAs>false</publicAsOnlySkipPeerAs>\n" +
                "                  <loadBalancingEnable>false</loadBalancingEnable>\n" +
                "                  <loadBalancingIgnoreAs>false</loadBalancingIgnoreAs>\n" +
                "                  <loadBalancingRelaxAs>false</loadBalancingRelaxAs>\n" +
                "                  <upgCfgIndependent>default</upgCfgIndependent>\n" +
                "                  <upgEffectIndependent>false</upgEffectIndependent>\n" +
                "                  <statisticsInfo>\n" +
                "                    <recvNLRINum>0</recvNLRINum>\n" +
                "                    <recvUNLRINum>0</recvUNLRINum>\n" +
                "                    <prePlyRouteNum>0</prePlyRouteNum>\n" +
                "                    <postPlyRouteNum>0</postPlyRouteNum>\n" +
                "                    <bestRouteNum>0</bestRouteNum>\n" +
                "                    <rejectedRtNum>0</rejectedRtNum>\n" +
                "                    <asPathLoopRtNum>0</asPathLoopRtNum>\n" +
                "                    <asConfLoopRtNum>0</asConfLoopRtNum>\n" +
                "                    <cluLoopRtNum>0</cluLoopRtNum>\n" +
                "                    <invalOrigRtNum>0</invalOrigRtNum>\n" +
                "                  </statisticsInfo>\n" +
                "                  <peerInfo>\n" +
                "                    <peerType>ebgp</peerType>\n" +
                "                    <version>4</version>\n" +
                "                    <remoteRouterId>0.0.0.0</remoteRouterId>\n" +
                "                    <bgpCurState>idle</bgpCurState>\n" +
                "                    <localPort>0</localPort>\n" +
                "                    <remotePort>0</remotePort>\n" +
                "                    <currentEvent>IHTimerExpired</currentEvent>\n" +
                "                    <bgpLastState>idle</bgpLastState>\n" +
                "                    <messageSent>0</messageSent>\n" +
                "                    <messageReceived>0</messageReceived>\n" +
                "                    <outQueue>0</outQueue>\n" +
                "                    <revHoldTime>0</revHoldTime>\n" +
                "                    <negoHoldTime>0</negoHoldTime>\n" +
                "                    <negoKeepAliveTime>0</negoKeepAliveTime>\n" +
                "                    <revUpdateCount>0</revUpdateCount>\n" +
                "                    <revOpenCount>0</revOpenCount>\n" +
                "                    <revKeepAliveCount>0</revKeepAliveCount>\n" +
                "                    <revNotificationCount>0</revNotificationCount>\n" +
                "                    <revRouteRefreshCount>0</revRouteRefreshCount>\n" +
                "                    <sentUpdateCount>0</sentUpdateCount>\n" +
                "                    <sentOpenCount>0</sentOpenCount>\n" +
                "                    <sentKeepAliveCount>0</sentKeepAliveCount>\n" +
                "                    <sentNotificationCount>0</sentNotificationCount>\n" +
                "                    <sentRouteRefreshCount>0</sentRouteRefreshCount>\n" +
                "                    <sendGRCapability>false</sendGRCapability>\n" +
                "                    <revRefreshCapability>false</revRefreshCapability>\n" +
                "                    <revFourByteASCapability>false</revFourByteASCapability>\n" +
                "                    <revSupportMPCapability>false</revSupportMPCapability>\n" +
                "                    <revGRCapability>false</revGRCapability>\n" +
                "                    <prefRecv>0</prefRecv>\n" +
                "                    <activePrefRecv>0</activePrefRecv>\n" +
                "                    <prefAdvertised>0</prefAdvertised>\n" +
                "                    <peerRpdCapability>null</peerRpdCapability>\n" +
                "                    <localRpdCapability>null</localRpdCapability>\n" +
                "                    <negotiatedRpdCapability>null</negotiatedRpdCapability>\n" +
                "                    <checkFirstAs>enable</checkFirstAs>\n" +
                "                    <peerExtNhpCap>false</peerExtNhpCap>\n" +
                "                  </peerInfo>\n" +
                "                </peerAF>\n" +
                "              </peerAFs>\n" +
                "            </bgpVrfAF>\n" +
                "          </bgpVrfAFs>\n" +
                "        </bgpVrf>\n" +
                "\t  </bgpVrfs>\n" +
                "    </bgpcomm>\n" +
                "  </bgp>\n" +
                "</data>";
    }

    public static String modify() {
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<data xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n" +
                "  <bgp xmlns=\"http://www.huawei.com/netconf/vrp/huawei-bgp\">\n" +
                "    <bgpcomm>\n" +
                "      <bgpVrfs>\n" +
                "        <bgpVrf>\n" +
                "          <vrfName>VPN-test</vrfName>\n" +
                "          <defaultAfType>ipv4uni</defaultAfType>\n" +
                "          <vrfRidAutoSel>false</vrfRidAutoSel>\n" +
                "          <effectRouterId>1.1.1.2</effectRouterId>\n" +
                "          <vrfSession>false</vrfSession>\n" +
                "          <bgpPeers>\n" +
                "            <bgpPeer>\n" +
                "              <peerAddr>192.168.1.4</peerAddr>\n" +
                "              <remoteAs>44</remoteAs>\n" +
                "              <routeRefresh>true</routeRefresh>\n" +
                "              <fourByteAs>true</fourByteAs>\n" +
                "              <conventional>false</conventional>\n" +
                "              <ebgpMaxHop>1</ebgpMaxHop>\n" +
                "              <isIgnore>false</isIgnore>\n" +
                "              <connectMode>null</connectMode>\n" +
                "              <isLogChange>true</isLogChange>\n" +
                "              <pswdType>null</pswdType>\n" +
                "              <keepAliveTime>60</keepAliveTime>\n" +
                "              <holdTime>180</holdTime>\n" +
                "              <pathMTUD>false</pathMTUD>\n" +
                "              <dualAs>false</dualAs>\n" +
                "              <trackingEnable>false</trackingEnable>\n" +
                "              <trackDelayTime>0</trackDelayTime>\n" +
                "              <connRetryTime>32</connRetryTime>\n" +
                "              <prependGlobalAs>false</prependGlobalAs>\n" +
                "              <prependFakeAs>false</prependFakeAs>\n" +
                "              <minHoldTime>0</minHoldTime>\n" +
                "              <checkFirstAs>default</checkFirstAs>\n" +
                "            </bgpPeer>\n" +
                "          </bgpPeers>\n" +
                "          <bgpVrfAFs>\n" +
                "            <bgpVrfAF>\n" +
                "              <afType>ipv4uni</afType>\n" +
                "              <asPathNeglect>false</asPathNeglect>\n" +
                "              <medNoneAsMaximum>false</medNoneAsMaximum>\n" +
                "              <alwaysCompareMed>false</alwaysCompareMed>\n" +
                "              <defaultLocalPref>100</defaultLocalPref>\n" +
                "              <defaultMed>0</defaultMed>\n" +
                "              <defaultRtImportEnable>false</defaultRtImportEnable>\n" +
                "              <maximumLoadBalance>1</maximumLoadBalance>\n" +
                "              <preferenceExternal>24</preferenceExternal>\n" +
                "              <preferenceInternal>24</preferenceInternal>\n" +
                "              <preferenceLocal>24</preferenceLocal>\n" +
                "              <reflectBetweenClient>true</reflectBetweenClient>\n" +
                "              <summaryAutomatic>false</summaryAutomatic>\n" +
                "              <routerIdNeglect>false</routerIdNeglect>\n" +
                "              <igpMetricIgnore>false</igpMetricIgnore>\n" +
                "              <autoFrrEnable>false</autoFrrEnable>\n" +
                "              <determinMed>false</determinMed>\n" +
                "              <ebgpIfSensitive>true</ebgpIfSensitive>\n" +
                "              <maxLoadEbgpNum>1</maxLoadEbgpNum>\n" +
                "              <maxLoadIbgpNum>1</maxLoadIbgpNum>\n" +
                "              <ecmpNexthopChanged>false</ecmpNexthopChanged>\n" +
                "              <eibgpEcmpNexthopChanged>false</eibgpEcmpNexthopChanged>\n" +
                "              <ebgpEcmpNexthopChanged>false</ebgpEcmpNexthopChanged>\n" +
                "              <ibgpEcmpNexthopChanged>false</ibgpEcmpNexthopChanged>\n" +
                "              <reflectChgPath>false</reflectChgPath>\n" +
                "              <vrfRidAutoSel>false</vrfRidAutoSel>\n" +
                "              <enBestRtBitErrDetection>false</enBestRtBitErrDetection>\n" +
                "              <activeRouteAdvertise>false</activeRouteAdvertise>\n" +
                "              <routeSelDelay>0</routeSelDelay>\n" +
                "              <originAsValid>false</originAsValid>\n" +
                "              <allowInvalidAs>false</allowInvalidAs>\n" +
                "              <originAsValidEnable>false</originAsValidEnable>\n" +
                "              <policyExtCommEnable>false</policyExtCommEnable>\n" +
                "              <supernetUniAdv>false</supernetUniAdv>\n" +
                "              <supernetLabelAdv>true</supernetLabelAdv>\n" +
                "              <loadBalancingIgpMetricIgnore>false</loadBalancingIgpMetricIgnore>\n" +
                "              <loadBalancingEibgp>false</loadBalancingEibgp>\n" +
                "              <loadBalancingAsPathIgnore>false</loadBalancingAsPathIgnore>\n" +
                "              <loadBalancingAsPathRelax>false</loadBalancingAsPathRelax>\n" +
                "              <originatorPrior>false</originatorPrior>\n" +
                "              <relayDelayEnable>true</relayDelayEnable>\n" +
                "              <medPlusIgp>false</medPlusIgp>\n" +
                "              <medMultiplier>1</medMultiplier>\n" +
                "              <igpMultiplier>1</igpMultiplier>\n" +
                "              <vrfImportnhpinvariable>false</vrfImportnhpinvariable>\n" +
                "              <slowPeerDet>true</slowPeerDet>\n" +
                "              <slowPeerThVal>300</slowPeerThVal>\n" +
                "              <slowPeerAbDet>true</slowPeerAbDet>\n" +
                "              <slowPeerAbThVal>9</slowPeerAbThVal>\n" +
                "              <aigp>false</aigp>\n" +
                "              <autoSid>false</autoSid>\n" +
                "              <srIpv6Mode>null</srIpv6Mode>\n" +
                "              <rpdPolicyChangeDelay>30</rpdPolicyChangeDelay>\n" +
                "              <advRouteMode>all</advRouteMode>\n" +
                "              <attrSetEnable>false</attrSetEnable>\n" +
                "              <evpnBgpAFConfig/>\n" +
                "              <vrfAFBriefInfo>\n" +
                "                <peerNum>1</peerNum>\n" +
                "                <routeNum>0</routeNum>\n" +
                "                <rdNum>0</rdNum>\n" +
                "              </vrfAFBriefInfo>\n" +
                "              <bgpRtStaticsInfo>\n" +
                "                <advRmTotalNum>0</advRmTotalNum>\n" +
                "                <activeRtNum>0</activeRtNum>\n" +
                "                <bestRtNum>0</bestRtNum>\n" +
                "                <addPathRtNum>0</addPathRtNum>\n" +
                "                <advBestRtNum>0</advBestRtNum>\n" +
                "                <cidrRtNum>0</cidrRtNum>\n" +
                "                <cmmyRtNum>0</cmmyRtNum>\n" +
                "                <diffOriAsRtNum>0</diffOriAsRtNum>\n" +
                "                <dampRtNum>0</dampRtNum>\n" +
                "                <ngType1RtNum>0</ngType1RtNum>\n" +
                "                <ngType2RtNum>0</ngType2RtNum>\n" +
                "                <ngType3RtNum>0</ngType3RtNum>\n" +
                "                <ngType4RtNum>0</ngType4RtNum>\n" +
                "                <ngType5RtNum>0</ngType5RtNum>\n" +
                "                <ngType6RtNum>0</ngType6RtNum>\n" +
                "                <ngType7RtNum>0</ngType7RtNum>\n" +
                "                <vrfRtNum>0</vrfRtNum>\n" +
                "                <lsNodeRtNum>0</lsNodeRtNum>\n" +
                "                <lsLinkRtNum>0</lsLinkRtNum>\n" +
                "                <lsIpv4PrefixRtNum>0</lsIpv4PrefixRtNum>\n" +
                "                <lsIpv6PrefixRtNum>0</lsIpv6PrefixRtNum>\n" +
                "              </bgpRtStaticsInfo>\n" +
                "              <peerAFs>\n" +
                "                <peerAF>\n" +
                "                  <remoteAddress>192.168.1.4</remoteAddress>\n" +
                "                  <advertiseCommunity>true</advertiseCommunity>\n" +
                "                  <advertiseExtCommunity>false</advertiseExtCommunity>\n" +
                "                  <discardExtCommunity>false</discardExtCommunity>\n" +
                "                  <allowAsLoopEnable>false</allowAsLoopEnable>\n" +
                "                  <defaultRtAdvEnable>false</defaultRtAdvEnable>\n" +
                "                  <defaultRtMatchMode>null</defaultRtMatchMode>\n" +
                "                  <keepAllRoutes>false</keepAllRoutes>\n" +
                "                  <nextHopConfigure>null</nextHopConfigure>\n" +
                "                  <preferredValue>0</preferredValue>\n" +
                "                  <publicAsOnly>false</publicAsOnly>\n" +
                "                  <rtUpdtInterval>30</rtUpdtInterval>\n" +
                "                  <reflectClient>false</reflectClient>\n" +
                "                  <substituteAsEnable>false</substituteAsEnable>\n" +
                "                  <importRtPolicyName>1</importRtPolicyName>\n" +
                "                  <exportRtPolicyName>2</exportRtPolicyName>\n" +
                "                  <labelRouteCapability>false</labelRouteCapability>\n" +
                "                  <checkTunnelReachable>false</checkTunnelReachable>\n" +
                "                  <originAsValid>false</originAsValid>\n" +
                "                  <publicAsOnlyForce>false</publicAsOnlyForce>\n" +
                "                  <publicAsOnlyLimited>false</publicAsOnlyLimited>\n" +
                "                  <publicAsOnlyReplace>false</publicAsOnlyReplace>\n" +
                "                  <publicAsOnlySkipPeerAs>false</publicAsOnlySkipPeerAs>\n" +
                "                  <loadBalancingEnable>false</loadBalancingEnable>\n" +
                "                  <loadBalancingIgnoreAs>false</loadBalancingIgnoreAs>\n" +
                "                  <loadBalancingRelaxAs>false</loadBalancingRelaxAs>\n" +
                "                  <upgCfgIndependent>default</upgCfgIndependent>\n" +
                "                  <upgEffectIndependent>false</upgEffectIndependent>\n" +
                "                  <statisticsInfo>\n" +
                "                    <recvNLRINum>0</recvNLRINum>\n" +
                "                    <recvUNLRINum>0</recvUNLRINum>\n" +
                "                    <prePlyRouteNum>0</prePlyRouteNum>\n" +
                "                    <postPlyRouteNum>0</postPlyRouteNum>\n" +
                "                    <bestRouteNum>0</bestRouteNum>\n" +
                "                    <rejectedRtNum>0</rejectedRtNum>\n" +
                "                    <asPathLoopRtNum>0</asPathLoopRtNum>\n" +
                "                    <asConfLoopRtNum>0</asConfLoopRtNum>\n" +
                "                    <cluLoopRtNum>0</cluLoopRtNum>\n" +
                "                    <invalOrigRtNum>0</invalOrigRtNum>\n" +
                "                  </statisticsInfo>\n" +
                "                  <peerInfo>\n" +
                "                    <peerType>ebgp</peerType>\n" +
                "                    <version>4</version>\n" +
                "                    <remoteRouterId>0.0.0.0</remoteRouterId>\n" +
                "                    <bgpCurState>idle</bgpCurState>\n" +
                "                    <localPort>0</localPort>\n" +
                "                    <remotePort>0</remotePort>\n" +
                "                    <currentEvent>IHTimerExpired</currentEvent>\n" +
                "                    <bgpLastState>idle</bgpLastState>\n" +
                "                    <messageSent>0</messageSent>\n" +
                "                    <messageReceived>0</messageReceived>\n" +
                "                    <outQueue>0</outQueue>\n" +
                "                    <revHoldTime>0</revHoldTime>\n" +
                "                    <negoHoldTime>0</negoHoldTime>\n" +
                "                    <negoKeepAliveTime>0</negoKeepAliveTime>\n" +
                "                    <revUpdateCount>0</revUpdateCount>\n" +
                "                    <revOpenCount>0</revOpenCount>\n" +
                "                    <revKeepAliveCount>0</revKeepAliveCount>\n" +
                "                    <revNotificationCount>0</revNotificationCount>\n" +
                "                    <revRouteRefreshCount>0</revRouteRefreshCount>\n" +
                "                    <sentUpdateCount>0</sentUpdateCount>\n" +
                "                    <sentOpenCount>0</sentOpenCount>\n" +
                "                    <sentKeepAliveCount>0</sentKeepAliveCount>\n" +
                "                    <sentNotificationCount>0</sentNotificationCount>\n" +
                "                    <sentRouteRefreshCount>0</sentRouteRefreshCount>\n" +
                "                    <sendGRCapability>false</sendGRCapability>\n" +
                "                    <revRefreshCapability>false</revRefreshCapability>\n" +
                "                    <revFourByteASCapability>false</revFourByteASCapability>\n" +
                "                    <revSupportMPCapability>false</revSupportMPCapability>\n" +
                "                    <revGRCapability>false</revGRCapability>\n" +
                "                    <prefRecv>0</prefRecv>\n" +
                "                    <activePrefRecv>0</activePrefRecv>\n" +
                "                    <prefAdvertised>0</prefAdvertised>\n" +
                "                    <peerRpdCapability>null</peerRpdCapability>\n" +
                "                    <localRpdCapability>null</localRpdCapability>\n" +
                "                    <negotiatedRpdCapability>null</negotiatedRpdCapability>\n" +
                "                    <checkFirstAs>enable</checkFirstAs>\n" +
                "                    <peerExtNhpCap>false</peerExtNhpCap>\n" +
                "                  </peerInfo>\n" +
                "                </peerAF>\n" +
                "              </peerAFs>\n" +
                "            </bgpVrfAF>\n" +
                "          </bgpVrfAFs>\n" +
                "        </bgpVrf>\n" +
                "      </bgpVrfs>\n" +
                "    </bgpcomm>\n" +
                "  </bgp>\n" +
                "</data>";
    }
}
