package cn.org.upbnc.xmlcompare;

public class ExplicitPathUtils {
    public static String running() {
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<data xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n" +
                "  <mpls xmlns=\"http://www.huawei.com/netconf/vrp/huawei-mpls\">\n" +
                "    <mplsTe>\n" +
                "      <explicitPaths>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel1000Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230020</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel1000Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230020</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel1Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322111</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322213</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322202</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel1Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322102</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel4Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322101</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322213</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322202</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel2Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322101</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230040</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322202</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel2Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322211</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel3Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322101</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322213</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322202</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel3Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322211</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel5Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322101</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322213</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322202</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel5Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322211</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel6Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230020</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel6Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230030</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230040</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230020</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "      </explicitPaths>\n" +
                "    </mplsTe>\n" +
                "  </mpls>\n" +
                "</data>";
    }

    public static String add() {
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<data xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n" +
                "  <mpls xmlns=\"http://www.huawei.com/netconf/vrp/huawei-mpls\">\n" +
                "    <mplsTe>\n" +
                "      <explicitPaths>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel1000Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230020</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel1000Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230020</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel1Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322111</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322213</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322202</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel1Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322102</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel4Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322101</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322213</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322202</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel2Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322101</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230040</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322202</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel2Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322211</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel3Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322101</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322213</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322202</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel3Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322211</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel5Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322101</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322213</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322202</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel5Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322211</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel6Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230020</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel6Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230030</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230040</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230020</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "\t\t        <explicitPath>\n" +
                "          <explicitPathName>Tunnel7Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230030</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230040</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230020</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "      </explicitPaths>\n" +
                "    </mplsTe>\n" +
                "  </mpls>\n" +
                "</data>";
    }

    public static String modify() {
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<data xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n" +
                "  <mpls xmlns=\"http://www.huawei.com/netconf/vrp/huawei-mpls\">\n" +
                "    <mplsTe>\n" +
                "      <explicitPaths>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel1000Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230020</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel1000Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230020</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel1Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322111</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322213</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322202</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel1Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322102</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel4Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322101</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322213</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322202</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel2Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322101</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230040</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322202</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel2Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322211</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel3Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322101</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322213</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322202</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel3Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322211</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel5Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322101</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322213</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322202</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel5Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>322211</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>adjacency</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel6Link</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230020</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "        <explicitPath>\n" +
                "          <explicitPathName>Tunnel6Linkback</explicitPathName>\n" +
                "          <explicitPathHops>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>1</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230031</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>2</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230041</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "            <explicitPathHop>\n" +
                "              <mplsTunnelHopIndex>3</mplsTunnelHopIndex>\n" +
                "              <mplsTunnelHopMode>SID_LABEL</mplsTunnelHopMode>\n" +
                "              <mplsTunnelHopSidLabel>230021</mplsTunnelHopSidLabel>\n" +
                "              <mplsTunnelHopSidLabelType>prefix</mplsTunnelHopSidLabelType>\n" +
                "            </explicitPathHop>\n" +
                "          </explicitPathHops>\n" +
                "        </explicitPath>\n" +
                "      </explicitPaths>\n" +
                "    </mplsTe>\n" +
                "  </mpls>\n" +
                "</data>";
    }
}
