package cn.org.upbnc.xmlcompare;

public class IfmUtils {
   public static String runing(){
       String xml="<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
               "<data xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n" +
               "  <ifm xmlns=\"http://www.huawei.com/netconf/vrp/huawei-ifm\">\n" +
               "    <interfaces>\n" +
               "      <interface>\n" +
               "        <ifName>Virtual-Template0</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>NULL0</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/0/0</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>192.168.1.3</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.0</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/0</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>192.168.10.2</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.0</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/1</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>10.1.10.3</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.0</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/2</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>10.1.1.1</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.0</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/3</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/4</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/5</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/6</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/22</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/24</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/7</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/8</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/9</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/10</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/11</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/12</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/13</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/14</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/15</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/16</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/17</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/18</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/19</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/20</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/21</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/23</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/25</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Eth-Trunk1</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>11.1.2.1</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.252</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/1.1</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/1.2</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/1.3</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>LoopBack0</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>1.1.1.1</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.255</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel1</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel900</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel1000</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel12341</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel2</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/1.4</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel3</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel4</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel1021</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel30</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel5</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel6</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel7</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel8</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel9</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel10</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel11</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel12</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel35</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>LoopBack1</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>192.168.200.3</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.255</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "    </interfaces>\n" +
               "  </ifm>\n" +
               "</data>";
       return xml;
   }

   public static String delete(){
       String xml="<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
               "<data xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n" +
               "  <ifm xmlns=\"http://www.huawei.com/netconf/vrp/huawei-ifm\">\n" +
               "    <interfaces>\n" +
               "      <interface>\n" +
               "        <ifName>Virtual-Template0</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>NULL0</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/0</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>192.168.10.2</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.0</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/1</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>10.1.10.3</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.0</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/2</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>10.1.1.1</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.0</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/3</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/4</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/5</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/6</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/22</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/24</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/7</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/8</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/9</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/10</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/11</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/12</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/13</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/14</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/15</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/16</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/17</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/18</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/19</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/20</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/21</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/23</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/25</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Eth-Trunk1</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>11.1.2.1</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.252</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/1.1</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/1.2</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/1.3</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>LoopBack0</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>1.1.1.1</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.255</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel1</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel900</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel1000</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel12341</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel2</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/1.4</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel3</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel4</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel1021</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel30</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel5</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel6</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel7</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel8</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel9</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel10</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel11</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel12</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel35</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>LoopBack1</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>192.168.200.3</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.255</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "    </interfaces>\n" +
               "  </ifm>\n" +
               "</data>";
       return xml;
   }

   public static String modify(){
       String xml="<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
               "<data xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n" +
               "  <ifm xmlns=\"http://www.huawei.com/netconf/vrp/huawei-ifm\">\n" +
               "    <interfaces>\n" +
               "      <interface>\n" +
               "        <ifName>Virtual-Template0</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>NULL0</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/0</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>192.168.10.200</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.0</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/1</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>10.1.10.3</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.0</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/2</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>10.1.1.1</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.0</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/3</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/4</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/5</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/6</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/22</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/24</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/7</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/8</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/9</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/10</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/11</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/12</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/13</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/14</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/15</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/16</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/17</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/18</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/19</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/20</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/21</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/23</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/25</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Eth-Trunk1</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>11.1.2.1</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.252</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/1.1</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/1.2</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/1.3</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>LoopBack0</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>1.1.1.1</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.255</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel1</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel900</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel1000</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel12341</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel2</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>GigabitEthernet0/3/1.4</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel3</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel4</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel1021</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel30</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel5</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel6</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel7</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel8</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel9</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel10</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel11</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel12</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>Tunnel35</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <unNumIfName>LoopBack0</unNumIfName>\n" +
               "          <addrCfgType>unnumbered</addrCfgType>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "      <interface>\n" +
               "        <ifName>LoopBack1</ifName>\n" +
               "        <ipv4Config>\n" +
               "          <addrCfgType>config</addrCfgType>\n" +
               "          <am4CfgAddrs>\n" +
               "            <am4CfgAddr>\n" +
               "              <ifIpAddr>192.168.200.3</ifIpAddr>\n" +
               "              <subnetMask>255.255.255.255</subnetMask>\n" +
               "              <addrType>main</addrType>\n" +
               "            </am4CfgAddr>\n" +
               "          </am4CfgAddrs>\n" +
               "        </ipv4Config>\n" +
               "      </interface>\n" +
               "    </interfaces>\n" +
               "  </ifm>\n" +
               "</data>";
       return xml;
   }
}
