package cn.org.upbnc.xmlcompare;

public class NodeLabelUtils {
    public static String running(){
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<data xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n" +
                "  <ospfv2 xmlns=\"http://www.huawei.com/netconf/vrp/huawei-ospfv2\">\n" +
                "    <ospfv2comm>\n" +
                "      <ospfSites>\n" +
                "        <ospfSite>\n" +
                "          <processId>65100</processId>\n" +
                "          <areas>\n" +
                "            <area>\n" +
                "              <areaId>0.0.0.0</areaId>\n" +
                "              <interfaces>\n" +
                "                <interface>\n" +
                "                  <ifName>GigabitEthernet0/3/2</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Eth-Trunk1</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>LoopBack0</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>absolute</prefixSidType>\n" +
                "                    <prefixLabel>230012</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel1</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel900</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel1000</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel2</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel3</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel4</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel5</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel6</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "              </interfaces>\n" +
                "            </area>\n" +
                "          </areas>\n" +
                "        </ospfSite>\n" +
                "      </ospfSites>\n" +
                "    </ospfv2comm>\n" +
                "  </ospfv2>\n" +
                "</data>";
    }
    public static String add(){
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<data xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n" +
                "  <ospfv2 xmlns=\"http://www.huawei.com/netconf/vrp/huawei-ospfv2\">\n" +
                "    <ospfv2comm>\n" +
                "      <ospfSites>\n" +
                "        <ospfSite>\n" +
                "          <processId>65100</processId>\n" +
                "          <areas>\n" +
                "            <area>\n" +
                "              <areaId>0.0.0.0</areaId>\n" +
                "              <interfaces>\n" +
                "                <interface>\n" +
                "                  <ifName>GigabitEthernet0/3/2</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Eth-Trunk1</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>LoopBack0</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>absolute</prefixSidType>\n" +
                "                    <prefixLabel>230012</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "\t\t\t\t                <interface>\n" +
                "                  <ifName>LoopBack1</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>absolute</prefixSidType>\n" +
                "                    <prefixLabel>230012</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel1</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel900</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel1000</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel2</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel3</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel4</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel5</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel6</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "              </interfaces>\n" +
                "            </area>\n" +
                "          </areas>\n" +
                "        </ospfSite>\n" +
                "      </ospfSites>\n" +
                "    </ospfv2comm>\n" +
                "  </ospfv2>\n" +
                "</data>";
    }
    public static String modify(){
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<data xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n" +
                "  <ospfv2 xmlns=\"http://www.huawei.com/netconf/vrp/huawei-ospfv2\">\n" +
                "    <ospfv2comm>\n" +
                "      <ospfSites>\n" +
                "        <ospfSite>\n" +
                "          <processId>65100</processId>\n" +
                "          <areas>\n" +
                "            <area>\n" +
                "              <areaId>0.0.0.0</areaId>\n" +
                "              <interfaces>\n" +
                "                <interface>\n" +
                "                  <ifName>GigabitEthernet0/3/2</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Eth-Trunk1</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>LoopBack0</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>absolute</prefixSidType>\n" +
                "                    <prefixLabel>230013</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel1</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel900</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel1000</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel2</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel3</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel4</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel5</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "                <interface>\n" +
                "                  <ifName>Tunnel6</ifName>\n" +
                "                  <srInterface>\n" +
                "                    <prefixSidType>no_set</prefixSidType>\n" +
                "                    <prefixLabel>0</prefixLabel>\n" +
                "                    <nodeFlag>true</nodeFlag>\n" +
                "                    <tiLfaDisable>false</tiLfaDisable>\n" +
                "                  </srInterface>\n" +
                "                </interface>\n" +
                "              </interfaces>\n" +
                "            </area>\n" +
                "          </areas>\n" +
                "        </ospfSite>\n" +
                "      </ospfSites>\n" +
                "    </ospfv2comm>\n" +
                "  </ospfv2>\n" +
                "</data>";
    }
}
